### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ifreund** [ifreund/river#1]
- [ ] river
	- [x] window management
		- [x] dwm-style tile layout
		- [x] atomic layout updates
		- [x] tags
			- [x] focus tag
			- [x] tag view
			- [x] toggle focus of tag
			- [x] toggle tag of view
			- [x] view all tags
			- [x] tag view with all tags
		- [x] focus stack
		- [x] external layouts (#28)
		- [x] fullscreen
		- [x] floating views
			- [x] implement
			- [x] moving
			- [x] resizing
	- [x] output
		- [x] multi monitor support
		- [x] expand atomic layout updates to handle output changes
		- [x] command to move views between outputs
	- [ ] input
		- [x] keybinding modes
		- [x] implicit cursor grabs
		- [ ] key repeat #70
		- [ ] libinput property configuration #71
		- [ ] multi-seat support
	- [ ] wayland protocols
		- [x] xdg-shell
			- [x] toplevels
			- [x] popups
		- [x] xdg-decoration
		- [x] xdg-output
		- [x] wlr-input-inhibit
			- [x] keyboard inhibit
			- [x] pointer inhibit
		- [x] wlr-screencopy
		- [x] wlr-layer-shell
			- [x] basic geometry
			- [x] exclusive zones
			- [x] keyboard handling
			- [x] cursor handling
			- [x] popups
		- [x] wlr-data-control
		- [x] wlr-gamma-control
		- [x] kde's idle protocol (used by swayidle)
		- [ ] xwayland
			- [x] basics
			- [ ] unmanaged views
				- [x] initial implementation
				- [ ] input handling
			- [ ] cursor theme handling
		- [x] wlr-output-management (see: https://git.sr.ht/~jf/tinywl-output-management)
		- [ ] and more...
	- [x] cosmetics
		- [x] borders
			- [x] change color on focus
		- [x] view padding
		- [x] outer padding
	- [ ] performance
		- [ ] implement damage tracking
		- [ ] investigate libliftoff and hardware planes
	- [x] misc
		- [x] handle vt switching
- [x] custom protocols
	- [x] river-control: run compositor commands.
	- [x] river-status: events for state changes to integrate with e.g. status bars.
- [x] riverctl

###	Before 0.1.0

River should be usable as a daily driver if you don't mind not having damage tracking. All core windowing behavior should be implemented. A protocol to make implementing bars possible should be finished.

###	Before 0.2.0

Big ticket item is damage tracking.

###	Before 1.0.0

To be decided...

**Comment by ifreund** [comment]
This roadmap was useful during the very early phases of the development, but at this stage it has grown much less useful. All relevant TODO items (and many others not listed here) have their own issue now.
