### ISSUE TITLE
Zig 0.7.0 todo

### ISSUE THREAD

**Issue by ifreund** [ifreund/river#3]
This is a list of fixes that will be possible after upgrading to zig 0.7.0 when it is released. This list will grow as more new features are added.

- [ ] Use `math.clamp` in `modifyMasterFactor()` https://github.com/ziglang/zig/pull/5074
- [ ] Use anon functions to make code more generic (e.g. a nice interface to iterate over all seats in `InputManager`) https://github.com/ziglang/zig/issues/1717
- [ ] Use `std.ComptimeStringMap` for commands
